import type { Content } from './types'
import { LINKS, PROJECT_LINKS } from './links'

export const en: Content = {
  ui: {
    menu: [
      { id: 'inicio', label: 'Home', place: 'Departure orbit' },
      { id: 'perfil', label: 'Profile', place: 'Orbital station' },
      { id: 'habilidades', label: 'Skills', place: 'Constellation field' },
      { id: 'experiencia', label: 'Missions', place: 'The ringed giant' },
      { id: 'projetos', label: 'Projects', place: 'Project system' },
      { id: 'contato', label: 'Contact', place: 'Relay beacon' },
    ],
    menuAriaLabel: 'Main menu',
    menuHeader: 'route · 6 stops',
    mobileNav: { prev: 'Previous section', next: 'Next section', sections: 'View all sections' },
    back: 'home',
    edgeHint: 'keep scrolling · next stop:',
    edgeHintPrev: 'keep scrolling · previous stop:',
    controlsHint: '↑ ↓ navigate · scroll to advance · Esc back',
    noWebgl: 'Your browser does not support WebGL, so the portfolio opened in a simplified version.',
    langLabel: 'Language',
    statusBar: { link: 'link stable', sector: 'sector', speed: 'vel', location: 'Uberlândia, Brazil' },
    boot: {
      kicker: 'a portfolio by',
      tasks: {
        fonts: 'fuelling the tanks',
        engine: 'starting the engines',
        stars: 'lighting the stars',
        orbit: 'plotting the orbit',
      },
      done: 'liftoff',
      ariaLabel: 'Loading the portfolio',
    },
    hero: {
      kicker: "Hi, I'm",
      now: 'I take a product from the database to the screen, and from there to production.',
      experience: 'About 2 years working in the field',
      resume: 'Download resume.pdf',
      scrollHint: 'scroll to lift off',
    },
    profile: { about: 'About', education: 'Education', studying: 'Studying now' },
    keys: { name: 'name', title: 'role', base: 'base', focus: 'focus', status: 'status' },
    skills: { hint: '// hover a group to light up its constellation' },
    missions: {
      counter: 'mission {current} of {total}',
      prev: 'Previous mission',
      next: 'Next mission',
      hint: '// ← → switch moons',
      telemetry: 'telemetry',
    },
    projects: {
      counter: 'planet {current} of {total}',
      prev: 'Previous project',
      next: 'Next project',
      repo: 'repository',
      demo: 'see it live',
      hint: '// ← → travel between planets',
      screen: 'scroll the page inside the screen',
    },
    contact: {
      title: 'Contact',
      lead: 'Reach me by email or on LinkedIn.',
      email: 'email',
      github: 'github',
      linkedin: 'linkedin',
          },
  },
  profile: {
    name: 'Leonardo Barros',
    title: 'Full Stack Developer',
    tagline: 'Next.js · React · TypeScript · Java · Node.js · PostgreSQL',
    focus: 'Integrations, authentication and performance',
    location: 'Uberlândia, MG · Brazil',
    status: 'Open to new opportunities',
    about: [
      "I'm a full stack developer and I like taking a product from the database to the screen, and from there to production.",
      'My most recent work was on an education and product catalog platform for a group in the dental industry, with users in several countries and three languages (Portuguese, Spanish and English).',
      'I have been working in the field for about 2 years. I also have experience with Java and with PHP/Laravel (Filament).',
    ],
    studying: 'Go, at Alura',
    links: LINKS,
  },
  skills: [
    { group: 'Languages', items: ['TypeScript', 'JavaScript', 'Java', 'SQL', 'PHP', 'Go (learning)'] },
    { group: 'Frontend', items: ['React', 'Next.js (App Router)', 'Tailwind CSS', 'shadcn/ui', 'PWA'] },
    { group: 'Backend', items: ['Node.js', 'Java', 'Supabase', 'Drizzle ORM', 'Laravel (Filament)'] },
    { group: 'Data', items: ['PostgreSQL', 'Supabase Auth + RLS'] },
    { group: 'Integrations', items: ['OAuth (Google, Microsoft, Apple)', 'HubSpot', 'HeyGen', 'Signed webhooks'] },
    { group: 'Web', items: ['Technical SEO', 'JSON-LD', 'hreflang', 'Performance (LCP)'] },
    { group: 'Infra and quality', items: ['Docker', 'GitHub Actions', 'Vercel', 'Playwright', 'Git'] },
  ],
  missions: [
    {
      company: 'Alliage Experience',
      role: 'Full Stack Developer',
      place: 'Education and product catalog platform · dental industry · PT, ES and EN',
      metrics: [
        { label: 'home page weight', from: '17.6 MB', to: '1.4 MB' },
        { label: 'LCP', from: '~10 s', to: '~1.3 s' },
      ],
      highlights: [
        'Authentication with email and password, Google, Microsoft and Apple.',
        'Automatic AI dubbing and subtitling of videos (HeyGen), with a processing queue, signed webhooks and cost control.',
        'Lead scoring integrated with HubSpot.',
        'Technical SEO: per-page metadata, JSON-LD, sitemap and hreflang.',
        'Full responsive pass, from 320 px up to desktop.',
        'Automatic deploys with GitHub Actions and Vercel.',
      ],
      stack: ['OAuth', 'HeyGen', 'HubSpot', 'JSON-LD', 'GitHub Actions', 'Vercel'],
    },
    {
      company: 'Central do Corretor',
      role: 'Full Stack Developer · from zero to deploy',
      place: 'Urba · MRV&CO Group · Parque Vista da Serra',
      highlights: [
        'Mobile-first internal tool for the brokers of the development.',
        'Sign-in with a code sent by email, plus access roles.',
        'Sales pitch, materials, FAQ, gallery and training audio in one place.',
        'Usage analytics, with spreadsheet export.',
      ],
      stack: ['Next.js 16', 'TypeScript', 'Supabase', 'Tailwind v4', 'shadcn/ui'],
    },
    {
      company: 'Imaginador',
      role: 'Front-end Developer · from zero to deploy',
      place: 'Urba · MRV&CO Group · Parque Vista da Serra',
      highlights: [
        'A sales experience that runs on a tablet at the sales stand.',
        'The client answers three questions and gets a personalised presentation, with their name, house facades and the neighbourhood.',
        'No backend, no build and no dependencies: it loads fast and runs on any tablet.',
      ],
      stack: ['HTML', 'CSS', 'JavaScript', 'Vercel'],
    },
  ],
  projects: [
    {
      title: 'Alliage Experience',
      kind: 'professional work',
      description:
        'Education and product catalog platform for a group in the dental industry, with users in several countries and three languages. Social login with OAuth (Google, Microsoft and Apple), AI video dubbing and subtitles through the HeyGen API (queue, signed webhooks and cost control), HubSpot lead scoring, technical SEO with JSON-LD and hreflang, and CI/CD with GitHub Actions and Vercel.',
      stack: ['Next.js', 'OAuth', 'HeyGen API', 'HubSpot', 'JSON-LD', 'hreflang', 'GitHub Actions', 'Vercel'],
      demo: PROJECT_LINKS.alliage.demo,
      site: {
        image: '/projetos/alliage-experience.webp',
        address: 'alliageexperience.com',
        alt: 'Alliage Experience home page, top to bottom',
      },
    },
    {
      title: 'Central do Corretor',
      kind: 'internal tool · Urba / MRV&CO',
      date: 'Jul 2026',
      description:
        'A mobile-first sales hub for the brokers of Parque Vista da Serra. Built with Next.js 16 (App Router), React 19 and TypeScript; Supabase for the Postgres database, email-code sign-in and access roles; UI with Tailwind v4, shadcn/ui and Framer Motion; forms validated with React Hook Form and Zod; reports exported to spreadsheets.',
      stack: ['Next.js 16', 'React 19', 'TypeScript', 'Supabase', 'Tailwind v4', 'shadcn/ui', 'Zod', 'Framer Motion'],
      demo: PROJECT_LINKS.central.demo,
      site: {
        image: '/projetos/central-do-corretor.webp',
        address: 'central-do-corretor.vercel.app',
        still: true,
        alt: 'Central do Corretor sign-in screen',
      },
    },
    {
      title: 'Imaginador',
      kind: 'sales experience · Urba / MRV&CO',
      date: 'Jul 2026',
      description:
        'Runs on a tablet at the Parque Vista da Serra sales stand: the client answers three questions and gets a personalised presentation of the development, with their name, facades in the chosen style and the neighbourhood. Plain HTML, CSS and JavaScript, with no backend, no build and no dependencies, deployed on Vercel.',
      stack: ['HTML', 'CSS', 'JavaScript', 'Vercel'],
      demo: PROJECT_LINKS.imaginador.demo,
      site: {
        image: '/projetos/imaginador.webp',
        address: 'imaginador.vercel.app/apresentacao',
        alt: 'Personalised presentation generated by Imaginador, top to bottom',
      },
    },
  ],
  education: [{ course: 'Developer track', school: 'Alura', period: '2024' }],
}
