import type { Content } from './types'
import { LINKS, PROJECT_LINKS } from './links'

export const pt: Content = {
  ui: {
    menu: [
      { id: 'inicio', label: 'Início', place: 'Órbita de partida' },
      { id: 'perfil', label: 'Perfil', place: 'Estação orbital' },
      { id: 'habilidades', label: 'Habilidades', place: 'Campo de constelações' },
      { id: 'experiencia', label: 'Missões', place: 'Gigante dos anéis' },
      { id: 'projetos', label: 'Projetos', place: 'Sistema de projetos' },
      { id: 'contato', label: 'Contato', place: 'Relé de transmissão' },
    ],
    menuAriaLabel: 'Menu principal',
    menuHeader: 'rota · 6 paradas',
    mobileNav: { prev: 'Seção anterior', next: 'Próxima seção', sections: 'Ver todas as seções' },
    back: 'início',
    edgeHint: 'continue rolando · próxima parada:',
    edgeHintPrev: 'continue rolando · parada anterior:',
    controlsHint: '↑ ↓ navegar · scroll avançar · Esc voltar',
    noWebgl: 'Seu navegador não suporta WebGL, então o portfólio abriu numa versão simplificada.',
    langLabel: 'Idioma',
    statusBar: { link: 'enlace estável', sector: 'setor', speed: 'vel', location: 'Uberlândia, MG' },
    boot: {
      kicker: 'um portfólio de',
      tasks: {
        fonts: 'abastecendo os tanques',
        engine: 'ligando os motores',
        stars: 'acendendo as estrelas',
        orbit: 'calculando a órbita',
      },
      done: 'decolagem',
      ariaLabel: 'Carregando o portfólio',
    },
    hero: {
      kicker: 'Olá, eu sou',
      now: 'Levo um produto do banco de dados até a tela, e de lá até a produção.',
      experience: 'Cerca de 2 anos atuando na área',
      resume: 'Baixar currículo.pdf',
      scrollHint: 'role para decolar',
    },
    profile: { about: 'Sobre', education: 'Formação', studying: 'Estudando agora' },
    keys: { name: 'nome', title: 'cargo', base: 'base', focus: 'foco', status: 'status' },
    skills: { hint: '// passe o cursor num grupo para acender a constelação' },
    missions: {
      counter: 'missão {current} de {total}',
      prev: 'Missão anterior',
      next: 'Próxima missão',
      hint: '// ← → trocam de lua',
      telemetry: 'telemetria',
    },
    projects: {
      counter: 'planeta {current} de {total}',
      prev: 'Projeto anterior',
      next: 'Próximo projeto',
      repo: 'repositório',
      demo: 'ver online',
      hint: '// ← → viajam entre os planetas',
      screen: 'role a página dentro da tela',
    },
    contact: {
      title: 'Contato',
      lead: 'Pode me chamar por e-mail ou pelo LinkedIn.',
      email: 'email',
      github: 'github',
      linkedin: 'linkedin',
          },
  },
  profile: {
    name: 'Leonardo Barros',
    title: 'Desenvolvedor Full Stack',
    tagline: 'Next.js · React · TypeScript · Java · Node.js · PostgreSQL',
    focus: 'Integrações, autenticação e performance',
    location: 'Uberlândia, MG · Brasil',
    status: 'Aberto a novas oportunidades',
    about: [
      'Sou desenvolvedor full stack e gosto de levar um produto do banco de dados até a tela, e de lá até a produção.',
      'Meu trabalho mais recente foi em uma plataforma de educação e catálogo de produtos para um grupo do setor odontológico, com usuários em vários países e três idiomas (português, espanhol e inglês).',
      'São cerca de 2 anos atuando na área. Também tenho experiência com Java e com PHP/Laravel (Filament).',
    ],
    studying: 'Go, na Alura',
    links: LINKS,
  },
  skills: [
    { group: 'Linguagens', items: ['TypeScript', 'JavaScript', 'Java', 'SQL', 'PHP', 'Go (estudando)'] },
    { group: 'Frontend', items: ['React', 'Next.js (App Router)', 'Tailwind CSS', 'shadcn/ui', 'PWA'] },
    { group: 'Backend', items: ['Node.js', 'Java', 'Supabase', 'Drizzle ORM', 'Laravel (Filament)'] },
    { group: 'Dados', items: ['PostgreSQL', 'Supabase Auth + RLS'] },
    { group: 'Integrações', items: ['OAuth (Google, Microsoft, Apple)', 'HubSpot', 'HeyGen', 'Webhooks assinados'] },
    { group: 'Web', items: ['SEO técnico', 'JSON-LD', 'hreflang', 'Performance (LCP)'] },
    { group: 'Infra e qualidade', items: ['Docker', 'GitHub Actions', 'Vercel', 'Playwright', 'Git'] },
  ],
  missions: [
    {
      company: 'Alliage Experience',
      role: 'Desenvolvedor Full Stack',
      place: 'Plataforma de educação e catálogo de produtos · setor odontológico · PT, ES e EN',
      metrics: [
        { label: 'peso da home', from: '17,6 MB', to: '1,4 MB' },
        { label: 'LCP', from: '~10 s', to: '~1,3 s' },
      ],
      highlights: [
        'Autenticação com e-mail e senha, Google, Microsoft e Apple.',
        'Dublagem e legenda automática de vídeos por IA (HeyGen), com fila de processamento, webhooks assinados e controle de custo.',
        'Lead scoring integrado ao HubSpot.',
        'SEO técnico: metadados por página, JSON-LD, sitemap e hreflang.',
        'Revisão responsiva completa, de 320 px ao desktop.',
        'Deploy automático com GitHub Actions e Vercel.',
      ],
      stack: ['OAuth', 'HeyGen', 'HubSpot', 'JSON-LD', 'GitHub Actions', 'Vercel'],
    },
    {
      company: 'Central do Corretor',
      role: 'Desenvolvedor Full Stack · do zero ao deploy',
      place: 'Urba · Grupo MRV&CO · Parque Vista da Serra',
      highlights: [
        'Ferramenta interna mobile-first para os corretores do empreendimento.',
        'Login por código enviado no e-mail e perfis de acesso.',
        'Discurso de vendas, materiais, FAQ, galeria e áudios de treinamento num só lugar.',
        'Analytics de uso, com exportação para planilha.',
      ],
      stack: ['Next.js 16', 'TypeScript', 'Supabase', 'Tailwind v4', 'shadcn/ui'],
    },
    {
      company: 'Imaginador',
      role: 'Desenvolvedor Front-end · do zero ao deploy',
      place: 'Urba · Grupo MRV&CO · Parque Vista da Serra',
      highlights: [
        'Experiência de vendas que roda num tablet, no plantão do empreendimento.',
        'O cliente responde três perguntas e recebe uma apresentação personalizada, com o nome dele, fachadas e o bairro.',
        'Sem backend, sem build e sem dependências: carrega rápido e funciona em qualquer tablet.',
      ],
      stack: ['HTML', 'CSS', 'JavaScript', 'Vercel'],
    },
  ],
  projects: [
    {
      title: 'Alliage Experience',
      kind: 'trabalho profissional',
      description:
        'Plataforma de educação e catálogo de produtos para um grupo do setor odontológico, com usuários em vários países e três idiomas. Login social com OAuth (Google, Microsoft e Apple), dublagem e legenda de vídeos por IA com a API da HeyGen (fila, webhooks assinados e controle de custo), lead scoring no HubSpot, SEO técnico com JSON-LD e hreflang, e CI/CD com GitHub Actions e Vercel.',
      stack: ['Next.js', 'OAuth', 'HeyGen API', 'HubSpot', 'JSON-LD', 'hreflang', 'GitHub Actions', 'Vercel'],
      demo: PROJECT_LINKS.alliage.demo,
      site: {
        image: '/projetos/alliage-experience.webp',
        address: 'alliageexperience.com',
        alt: 'Home da Alliage Experience, do topo ao rodapé',
      },
    },
    {
      title: 'Central do Corretor',
      kind: 'ferramenta interna · Urba / MRV&CO',
      date: 'Jul 2026',
      description:
        'Central de vendas mobile-first para os corretores do Parque Vista da Serra. Feita em Next.js 16 (App Router) com React 19 e TypeScript; Supabase para o banco Postgres, login por código no e-mail e perfis de acesso; interface com Tailwind v4, shadcn/ui e Framer Motion; formulários validados com React Hook Form e Zod; relatórios exportados em planilha.',
      stack: ['Next.js 16', 'React 19', 'TypeScript', 'Supabase', 'Tailwind v4', 'shadcn/ui', 'Zod', 'Framer Motion'],
      demo: PROJECT_LINKS.central.demo,
      site: {
        image: '/projetos/central-do-corretor.webp',
        address: 'central-do-corretor.vercel.app',
        still: true,
        alt: 'Tela de login da Central do Corretor',
      },
    },
    {
      title: 'Imaginador',
      kind: 'experiência de vendas · Urba / MRV&CO',
      date: 'Jul 2026',
      description:
        'Roda num tablet no plantão de vendas do Parque Vista da Serra: o cliente responde três perguntas e recebe uma apresentação personalizada do empreendimento, com o nome dele, fachadas no estilo escolhido e o bairro. Feito em HTML, CSS e JavaScript puros, sem backend, sem build e sem dependências, publicado na Vercel.',
      stack: ['HTML', 'CSS', 'JavaScript', 'Vercel'],
      demo: PROJECT_LINKS.imaginador.demo,
      site: {
        image: '/projetos/imaginador.webp',
        address: 'imaginador.vercel.app/apresentacao',
        alt: 'Apresentação personalizada gerada pelo Imaginador, do topo ao rodapé',
      },
    },
  ],
  education: [{ course: 'Formação dev', school: 'Alura', period: '2024' }],
}
